import type { CmsBoat, CmsPriceRow } from "@/lib/site-content";

const SEASON_LOW = "Basse saison · 16 sept. – 14 juin";
const SEASON_HIGH = "Haute saison · 15 juin – 15 sept.";
const NOTE_FUEL = "Tarifs hors carburant";
const NOTE_ELEC = "Tarifs TTC — bateau électrique";

function rows(
  items: Array<[string, number | null, number | null]>,
): CmsPriceRow[] {
  return items.map(([label, lowSeason, highSeason], i) => ({
    id: `r${i + 1}`,
    label,
    lowSeason,
    highSeason,
  }));
}

/** Flotte JCF Boat — photo .1 = image catalogue, .2+ = galerie (ordre d’empilement). */
export const DEFAULT_FLEET: CmsBoat[] = [
  {
    id: "mana23",
    slug: "mana-23",
    name: "MANA 23",
    year: 2023,
    type: "Coque rigide",
    category: "standard",
    capacity: 6,
    pricePerDay: 550,
    priceHalfDay: 350,
    location: "Port de Cassis",
    rating: 5,
    image: "/mana23.1.jpg",
    gallery: ["/mana23.2.jpg", "/mana23.3.jpg", "/mana23.4.jpg"],
    available: true,
    published: true,
    featured: true,
    displayOrder: 1,
    tags: ["Confort", "Familial"],
    shortDescription: "Rand Mana 7 m — spacieux, grand confort pour 6 personnes.",
    description:
      "Day cruiser confortable pour explorer les calanques. Salon, grande table de repas et plage de soleil pour une journée en mer détendue.",
    seoTitle: "MANA 23 Rand Mana à louer à Cassis",
    seoDescription:
      "Louez le MANA 23 (Rand Mana 7 m, Mercury 60 CV, 6 pers.) à Cassis. Tarifs demi-journée et journée, hors carburant.",
    length: "7 m",
    motor: "Mercury 60 CV",
    license: "Permis côtier requis",
    features: [
      "Taud de protection solaire",
      "Échelle de bain",
      "Plateforme de bain",
      "Grande table de repas",
      "Salon",
      "Plage de soleil",
    ],
    includedServices: ["Briefing sécurité", "Gilets de sauvetage"],
    optionalServices: [],
    pricingNote: NOTE_FUEL,
    lowSeasonLabel: SEASON_LOW,
    highSeasonLabel: SEASON_HIGH,
    pricingRows: rows([
      ["9h – 13h", 300, 350],
      ["14h – 19h", 400, 450],
      ["9h – 16h", 450, 550],
      ["17h – 20h", null, 300],
    ]),
  },
  {
    id: "eoleII",
    slug: "eole-ii",
    name: "EOLE II",
    year: 2023,
    type: "Semi-rigide",
    category: "standard",
    capacity: 8,
    pricePerDay: 700,
    priceHalfDay: 400,
    location: "Port de Cassis",
    rating: 5,
    image: "/eoleII.1.jpg",
    gallery: ["/eoleII.2.jpg", "/eoleII.3.jpg"],
    available: true,
    published: true,
    featured: true,
    displayOrder: 2,
    tags: ["Semi-rigide", "GPS"],
    shortDescription: "BSC 70 — 7 m, Yamaha 175 CV, jusqu’à 8 personnes.",
    description:
      "Semi-rigide polyvalent pour les calanques : guindeau électrique, bain de soleil et GPS pour naviguer en confiance.",
    seoTitle: "EOLE II BSC 70 à louer à Cassis",
    seoDescription:
      "Louez EOLE II (BSC 70, Yamaha 175 CV, 8 pers.) à Cassis. Semi-rigide avec guindeau, GPS et taud.",
    length: "7 m",
    motor: "Yamaha 175 CV",
    license: "Permis côtier requis",
    features: [
      "Guindeau électrique",
      "Bain de soleil",
      "Taud de protection solaire",
      "Douchette",
      "Échelle de bain",
      "GPS",
    ],
    includedServices: ["Briefing sécurité", "Gilets de sauvetage"],
    optionalServices: [],
    pricingNote: NOTE_FUEL,
    lowSeasonLabel: SEASON_LOW,
    highSeasonLabel: SEASON_HIGH,
    pricingRows: rows([
      ["9h – 13h", 350, 400],
      ["14h – 19h", 450, 550],
      ["9h – 16h", 600, 700],
      ["17h – 20h", null, 350],
    ]),
  },
  {
    id: "emmaII",
    slug: "emma-ii",
    name: "EMMA II",
    year: 2023,
    type: "Semi-rigide",
    category: "standard",
    capacity: 6,
    pricePerDay: 450,
    priceHalfDay: 300,
    location: "Port de Cassis",
    rating: 5,
    image: "/emmaII.1.png",
    gallery: ["/emmaII.2.jpg", "/emmaII.3.jpg"],
    available: true,
    published: true,
    featured: true,
    displayOrder: 3,
    tags: ["Semi-rigide"],
    shortDescription: "BSC 57 — 5,70 m, Yamaha 100 CV, 6 personnes.",
    description:
      "Semi-rigide compact et bien équipé pour une sortie entre amis ou en famille dans les calanques.",
    seoTitle: "EMMA II BSC 57 à louer à Cassis",
    seoDescription:
      "Louez EMMA II (BSC 57, Yamaha 100 CV, 6 pers.) à Cassis. Semi-rigide avec bain de soleil, taud et douchette.",
    length: "5,70 m",
    motor: "Yamaha 100 CV",
    license: "Permis côtier requis",
    features: [
      "Bain de soleil",
      "Taud de protection solaire",
      "Douchette",
      "Échelle de bain",
      "GPS",
    ],
    includedServices: ["Briefing sécurité", "Gilets de sauvetage"],
    optionalServices: [],
    pricingNote: NOTE_FUEL,
    lowSeasonLabel: SEASON_LOW,
    highSeasonLabel: SEASON_HIGH,
    pricingRows: rows([
      ["9h – 13h", 240, 300],
      ["14h – 19h", 300, 380],
      ["9h – 16h", 350, 450],
      ["17h – 20h", null, 260],
    ]),
  },
  {
    id: "samosIII",
    slug: "samos-iii",
    name: "SAMOS III",
    year: 2023,
    type: "Semi-rigide",
    category: "standard",
    capacity: 6,
    pricePerDay: 450,
    priceHalfDay: 300,
    location: "Port de Cassis",
    rating: 5,
    image: "/samosIII.1.png",
    gallery: ["/samosIII.2.jpeg"],
    available: true,
    published: true,
    featured: false,
    displayOrder: 4,
    tags: ["Semi-rigide", "Calanques"],
    shortDescription: "Capelli Tempest 570 — Yamaha 100 CV, 6 personnes.",
    description:
      "Semi-rigide confortable et spacieux, idéal pour découvrir les calanques entre amis.",
    seoTitle: "SAMOS III Capelli Tempest 570 à Cassis",
    seoDescription:
      "Louez SAMOS III (Capelli Tempest 5,70 m, Yamaha 100 CV, 6 pers.) à Cassis.",
    length: "5,70 m",
    motor: "Yamaha 100 CV",
    license: "Permis côtier requis",
    features: [
      "Bain de soleil",
      "Douchette",
      "Taud de soleil",
      "Échelle de bain",
    ],
    includedServices: ["Briefing sécurité", "Gilets de sauvetage"],
    optionalServices: [],
    pricingNote: NOTE_FUEL,
    lowSeasonLabel: SEASON_LOW,
    highSeasonLabel: SEASON_HIGH,
    pricingRows: rows([
      ["9h – 13h", 240, 300],
      ["9h – 16h", 350, 450],
      ["14h – 19h", 300, 380],
      ["17h – 20h", null, 260],
    ]),
  },
  {
    id: "thaisIV",
    slug: "thais-iv",
    name: "THAIS IV",
    year: 2023,
    type: "Semi-rigide",
    category: "standard",
    capacity: 10,
    pricePerDay: 750,
    priceHalfDay: 450,
    location: "Port de Cassis",
    rating: 5,
    image: "/thaisIV.1.jpg",
    gallery: ["/thaisIV.2.jpeg", "/thaisIV.3.jpeg"],
    available: true,
    published: true,
    featured: true,
    displayOrder: 5,
    tags: ["10 personnes", "Guindeau"],
    shortDescription: "Capelli Tempest 700 — 200 CV, jusqu’à 10 personnes.",
    description:
      "Grand semi-rigide confortable en navigation et au mouillage, avec guindeau électrique et vaste bain de soleil.",
    seoTitle: "THAIS IV Capelli Tempest 700 à Cassis",
    seoDescription:
      "Louez THAIS IV (Capelli Tempest 700, 200 CV, 10 pers.) à Cassis. Guindeau, GPS et grand bain de soleil.",
    length: "7 m",
    motor: "200 CV",
    license: "Permis côtier requis",
    features: [
      "Grand bain de soleil",
      "Taud de protection solaire",
      "Douchette",
      "Guindeau électrique",
      "GPS",
    ],
    includedServices: ["Briefing sécurité", "Gilets de sauvetage"],
    optionalServices: [],
    pricingNote: NOTE_FUEL,
    lowSeasonLabel: SEASON_LOW,
    highSeasonLabel: SEASON_HIGH,
    pricingRows: rows([
      ["9h – 13h", 350, 450],
      ["9h – 16h", 650, 750],
      ["14h – 19h", 500, 600],
      ["17h – 20h", null, 380],
    ]),
  },
  {
    id: "salt-e",
    slug: "salt-e",
    name: "SALT-E",
    year: 2024,
    type: "Sans permis",
    category: "electrique",
    capacity: 4,
    pricePerDay: 350,
    priceHalfDay: 230,
    location: "Port de Cassis",
    rating: 5,
    image: "/salt-e.1.jpg",
    gallery: ["/salt-e.2.jpg", "/salt-e.3.jpg", "/salt-e.4.png"],
    available: true,
    published: true,
    featured: true,
    displayOrder: 6,
    tags: ["Sans permis", "Électrique"],
    shortDescription: "Sans permis 100 % électrique — 5,5 m, 4 personnes.",
    description:
      "Bateau électrique silencieux, spacieux, avec grand bain de soleil. Panneaux solaires pour une navigation sereine dans les calanques.",
    seoTitle: "SALT-E bateau électrique sans permis à Cassis",
    seoDescription:
      "Louez le SALT-E, bateau sans permis 100 % électrique pour 4 personnes à Cassis.",
    length: "5,5 m",
    motor: "100 % électrique · panneaux solaires",
    license: "Sans permis",
    features: [
      "Grand bain de soleil",
      "Échelle de bain",
      "Volant",
      "Taud de protection solaire",
    ],
    includedServices: ["Briefing sécurité", "Gilets de sauvetage"],
    optionalServices: [],
    pricingNote: NOTE_ELEC,
    lowSeasonLabel: SEASON_LOW,
    highSeasonLabel: SEASON_HIGH,
    pricingRows: rows([
      ["3 h · 9h – 12h", 220, 230],
      ["3 h · 15h – 18h", 220, 250],
      ["4 h 30 · 15h – 19h30", 320, 350],
    ]),
  },
  {
    id: "marinello-e",
    slug: "marinello-e",
    name: "MARINELLO-E",
    year: 2024,
    type: "Sans permis",
    category: "electrique",
    capacity: 4,
    pricePerDay: 350,
    priceHalfDay: 230,
    location: "Port de Cassis",
    rating: 5,
    image: "/marinello-e.1.png",
    gallery: [],
    available: true,
    published: true,
    featured: false,
    displayOrder: 7,
    tags: ["Sans permis", "Électrique"],
    shortDescription: "Sans permis 100 % électrique — 5 m, 4 personnes.",
    description:
      "Bateau électrique simple et confortable pour découvrir Cassis sans permis, avec bain de soleil et taud.",
    seoTitle: "MARINELLO-E électrique sans permis à Cassis",
    seoDescription:
      "Louez le MARINELLO-E, bateau sans permis 100 % électrique pour 4 personnes à Cassis.",
    length: "5 m",
    motor: "100 % électrique",
    license: "Sans permis",
    features: [
      "Bain de soleil",
      "Échelle de bain",
      "Volant",
      "Taud de protection solaire",
    ],
    includedServices: ["Briefing sécurité", "Gilets de sauvetage"],
    optionalServices: [],
    pricingNote: NOTE_ELEC,
    lowSeasonLabel: SEASON_LOW,
    highSeasonLabel: SEASON_HIGH,
    pricingRows: rows([
      ["3 h · 9h – 12h", 220, 230],
      ["3 h · 15h – 18h", 220, 250],
      ["4 h 30 · 15h – 19h30", 320, 350],
    ]),
  },
  {
    id: "inesV",
    slug: "ines-v",
    name: "INES V",
    year: 2023,
    type: "Open",
    category: "standard",
    capacity: 5,
    pricePerDay: 400,
    priceHalfDay: 240,
    location: "Port de Cassis",
    rating: 5,
    image: "/inesV.1.jpeg",
    gallery: ["/inesV.2.jpeg"],
    available: true,
    published: true,
    featured: false,
    displayOrder: 8,
    tags: ["Familial"],
    shortDescription: "Pacific Craft 500 — Yamaha 50 CV, 5 personnes.",
    description:
      "Facilement manœuvrable, confortable en mer. Idéal pour une famille avec enfants.",
    seoTitle: "INES V Pacific Craft 500 à louer à Cassis",
    seoDescription:
      "Louez INES V (Pacific Craft 500, Yamaha 50 CV, 5 pers.) à Cassis. Idéal familles.",
    length: "5 m",
    motor: "Yamaha 4 temps 50 CV",
    license: "Permis côtier requis",
    features: [
      "Taud de soleil",
      "Échelle de bain",
      "Bain de soleil",
      "Gilets de sauvetage",
      "Carte de navigation",
    ],
    includedServices: ["Briefing sécurité"],
    optionalServices: [],
    pricingNote: NOTE_FUEL,
    lowSeasonLabel: SEASON_LOW,
    highSeasonLabel: SEASON_HIGH,
    pricingRows: rows([
      ["9h – 13h", 190, 240],
      ["9h – 16h", 320, 400],
      ["14h – 19h", 240, 320],
      ["17h – 20h", null, 220],
    ]),
  },
  {
    id: "lesbosIII",
    slug: "lesbos-iii",
    name: "LESBOS III",
    year: 2023,
    type: "Open",
    category: "standard",
    capacity: 6,
    pricePerDay: 450,
    priceHalfDay: 300,
    location: "Port de Cassis",
    rating: 5,
    image: "/lesbosIII.1.jpg",
    gallery: ["/lesbosIII.2.jpeg", "/lesbosIII.3.jpeg"],
    available: true,
    published: true,
    featured: false,
    displayOrder: 9,
    tags: ["Familial"],
    shortDescription: "Pacific Craft 545 — Yamaha 100 CV, 6 personnes.",
    description:
      "Confortable et spacieux, idéal pour une balade en famille dans les calanques.",
    seoTitle: "LESBOS III Pacific Craft 545 à Cassis",
    seoDescription:
      "Louez LESBOS III (Pacific Craft 545, Yamaha 100 CV, 6 pers.) à Cassis.",
    length: "5,45 m",
    motor: "Yamaha 100 CV",
    license: "Permis côtier requis",
    features: ["Bain de soleil", "Taud de soleil", "Douchette", "Échelle de bain"],
    includedServices: ["Briefing sécurité", "Gilets de sauvetage"],
    optionalServices: [],
    pricingNote: NOTE_FUEL,
    lowSeasonLabel: SEASON_LOW,
    highSeasonLabel: SEASON_HIGH,
    pricingRows: rows([
      ["9h – 13h", 240, 300],
      ["9h – 16h", 350, 450],
      ["14h – 19h", 300, 380],
      ["17h – 20h", null, 260],
    ]),
  },
  {
    id: "naxosIII",
    slug: "naxos-iii",
    name: "NAXOS III",
    year: 2023,
    type: "Sun cruiser",
    category: "standard",
    capacity: 8,
    pricePerDay: 700,
    priceHalfDay: 400,
    location: "Port de Cassis",
    rating: 5,
    image: "/naxosIII.1.png",
    gallery: ["/naxosIII.2.jpeg", "/naxosIII.3.jpeg"],
    available: true,
    published: true,
    featured: false,
    displayOrder: 10,
    tags: ["Sun cruiser", "Guindeau"],
    shortDescription: "Pacific Craft 700 Sun Cruiser — Yamaha 175 CV, 8 pers.",
    description:
      "Très confortable pour une journée en calanques : grand bain de soleil, guindeau électrique, douchette et GPS.",
    seoTitle: "NAXOS III Pacific Craft 700 à Cassis",
    seoDescription:
      "Louez NAXOS III (Pacific Craft 700, Yamaha 175 CV, 8 pers.) à Cassis.",
    length: "7 m",
    motor: "Yamaha 4 temps 175 CV",
    license: "Permis côtier requis",
    features: [
      "Grand bain de soleil",
      "Douchette",
      "Taud de soleil",
      "GPS",
      "Guindeau électrique",
    ],
    includedServices: ["Briefing sécurité", "Gilets de sauvetage"],
    optionalServices: [],
    pricingNote: NOTE_FUEL,
    lowSeasonLabel: SEASON_LOW,
    highSeasonLabel: SEASON_HIGH,
    pricingRows: rows([
      ["Matin · 9h – 13h", 350, 400],
      ["Journée · 9h – 16h", 600, 700],
      ["Après-midi · 14h – 19h", 450, 550],
      ["Soirée · 17h – 20h", null, 350],
    ]),
  },
  {
    id: "milosII",
    slug: "milos-ii",
    name: "MILOS II",
    year: 2023,
    type: "Semi-rigide",
    category: "standard",
    capacity: 7,
    pricePerDay: 550,
    priceHalfDay: 350,
    location: "Port de Cassis",
    rating: 5,
    image: "/milosII.1.jpg",
    gallery: ["/milosII.2.jpg"],
    available: true,
    published: true,
    featured: false,
    displayOrder: 11,
    tags: ["Semi-rigide", "Économe"],
    shortDescription: "BSC 65 — 6,50 m, Yamaha 115 CV, 7 personnes.",
    description:
      "Semi-rigide confortable en navigation comme à l’ancre, faible consommation. Guindeau électrique et douche de pont.",
    seoTitle: "MILOS II BSC 65 à louer à Cassis",
    seoDescription:
      "Louez MILOS II (BSC 65, Yamaha 115 CV, 7 pers.) à Cassis. Semi-rigide confortable et économe.",
    length: "6,50 m",
    motor: "Yamaha 4 temps 115 CV",
    license: "Permis côtier requis",
    features: [
      "Taud de soleil",
      "Douchette",
      "Bain de soleil",
      "Guindeau électrique",
      "Échelle de bain",
      "GPS",
    ],
    includedServices: ["Briefing sécurité", "Gilets de sauvetage"],
    optionalServices: [],
    pricingNote: NOTE_FUEL,
    lowSeasonLabel: SEASON_LOW,
    highSeasonLabel: SEASON_HIGH,
    pricingRows: rows([
      ["9h – 13h", 300, 350],
      ["9h – 16h", 450, 550],
      ["14h – 19h", 400, 450],
      ["17h – 20h", null, 300],
    ]),
  },
  {
    id: "e-mana",
    slug: "e-mana",
    name: "E-MANA",
    year: 2024,
    type: "Coque rigide",
    category: "electrique",
    capacity: 6,
    pricePerDay: 400,
    priceHalfDay: 300,
    location: "Port de Cassis",
    rating: 5,
    image: "/e-mana.1.jpg",
    gallery: ["/e-mana.2.jpg", "/e-mana.3.jpg", "/e-mana.4.jpg"],
    available: true,
    published: true,
    featured: true,
    displayOrder: 12,
    tags: ["Électrique", "Nouveauté", "Avec permis"],
    shortDescription: "Rand Mana 7 m — 100 % électrique, avec permis, 6 pers.",
    description:
      "Nouveauté électrique à coque rigide. Spacieux et silencieux pour découvrir les calanques en toute quiétude — moteur Torqeedo 10 kW.",
    seoTitle: "E-MANA Rand Mana électrique à Cassis",
    seoDescription:
      "Louez l’E-MANA (Rand Mana 7 m, Torqeedo 10 kW, 6 pers.) à Cassis. 100 % électrique avec permis.",
    length: "7 m",
    motor: "Torqeedo 10 kW · 100 % électrique",
    license: "Permis côtier requis",
    features: [
      "GPS",
      "Bain de soleil avec coussins",
      "Table",
      "Échelle de bain",
      "Taud de soleil",
      "Douchette",
    ],
    includedServices: ["Briefing sécurité", "Gilets de sauvetage"],
    optionalServices: [],
    pricingNote: `${NOTE_ELEC} · Créneaux 3 h selon saison`,
    lowSeasonLabel: `${SEASON_LOW} · 9h–12h / 14h–17h`,
    highSeasonLabel: `${SEASON_HIGH} · 9h–12h / 15h–18h`,
    pricingRows: rows([["Créneau 3 h", 300, 400]]),
  },
];
